# Basic operations with Matrices

In [2]:
import numpy as np

In [12]:
# Create 1-D array (called a vector)
x = np.array([1,2,3,4])
print(x)
print()
print(x.shape)
print(len(x))

[1 2 3 4]

(4,)
4


In [25]:
# Create a 3x2 array (called a matrix of order (3,2))
A = np.array([[1,2],[3,4],[5,6]])
print(A)
print()
print(A.shape)

B = np.array([[2,5],[7,4],[4,3]])
print()
print(B)

[[1 2]
 [3 4]
 [5 6]]

(3, 2)

[[2 5]
 [7 4]
 [4 3]]


### Transposing a matrix

In [27]:
A_T = A.transpose()
print(A_T)
print()

# Or simply
B_T = B.T
print(B_T)

[[1 3 5]
 [2 4 6]]

[[2 7 4]
 [5 4 3]]


### Matrix Addition

In [37]:
C = A + B
print(A, B, C, sep="\n\n")

[[1 2]
 [3 4]
 [5 6]]

[[2 5]
 [7 4]
 [4 3]]

[[ 3  7]
 [10  8]
 [ 9  9]]


In [35]:
D = C + 1
print(C, D, sep="\n\n")

[[ 3  7]
 [10  8]
 [ 9  9]]

[[ 4  8]
 [11  9]
 [10 10]]


### Matrix Multipllication

In [44]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[1,2,3],[4,5,6]])
C = np.dot(A,B)                   # np function
D = B.dot(A)                      # np.ndarray method

print(A,B,C, sep="\n\n")
print("\n\n")
print(B,A,D, sep="\n\n")

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]



[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[22 28]
 [49 64]]


### Identity Matrices

An Identity matrix is a square matrix with 1's on the diagonal and 0's everywhere else.

It's special because when you multiply it with another Matrix the result is the same Matrix.

The numpy function `np.eye(n)` will generate an identity matrix with dimensions n by n

In [55]:
I = np.eye(3, dtype="int")
IA = I.dot(A)
print(I, A, IA, sep="\n\n")

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2]
 [3 4]
 [5 6]]


### The Determinant

The determinant has something to do with finding the inverse of a matrix. It's kinda confusing, but of course once you find the inverse of a matrix that means you can divide a matrix.

The matrix must be a square matrix to find the determinant

In [56]:
M = np.array([[1,2],[3,4]])
determinant = np.linalg.det(M)
print(M)
print(determinant)

[[1 2]
 [3 4]]
-2.0000000000000004


In this case there is a rounding error? because computing the determinant for a (2,2) matrix is easy. 

topleft*bottomright - topright*bottomleft

1*4 - 2*3 = 4 - 6 = -2

with square matrices larger and 2 by 2 you have to do something called co-factor expansion which is complicated

### Inverse Matrices

In [59]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)

print(A, A_inv, I, sep="\n\n")

[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


again there is a rounding error here for some reason. But -5.5e-17 is clearly practically zero.