**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [22]:
x = np.array([1,2,3])
print(x)
print(x.shape)

[1 2 3]
(3,)


**TASK:** define (2 x 2) matrix 'A' 


In [23]:
A = np.array([[0,1],[2,3]])
print(A)

[[0 1]
 [2 3]]


**TASK:** define (2 x 2) matrix 'B'

In [24]:
B = np.array([[1,2],[3,4]])
print(B)

[[1 2]
 [3 4]]


**TASK:** check the type of 'x'

In [25]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [26]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [27]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [28]:
A.shape

(2, 2)

**TASK:** 

In [29]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [30]:
A.shape == x.shape

False

In [33]:
def have_same_shape(array_1, array_2):
    if array_1.shape != array_2.shape: print("Arrays must have same shape!")
    return array_1.shape == array_2.shape

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [34]:
have_same_shape(A, x)

Arrays must have same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [35]:
have_same_shape(A, B)

True

**TASK:** 

In [36]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


"\nDefine function 'matrix_addition' which perform matrix addition value by value.\n\nPARAMS:\n    A (numpy.ndarray) - first array\n    B (numpy.ndarray) - second array\nRETURN:\n    C (numpy.ndarray) - new A+B array\n\nIn this task do not consider broadcasting.\nDo not forget to check arrays shapes (you can use 'have_same_shape' function defined before)\n\n"

In [53]:
def matrix_addition(A, B):
    if have_same_shape(A, B):
        return A + B

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [57]:
matrix_addition(A, B)

array([[1, 3],
       [5, 7]])

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_addition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [75]:
def multiple_matrix_addition(arr_list):
    A = matrix_addition(arr_list[0], arr_list[1])
    for i in range(2, len(arr_list)):
        A = matrix_addition(A, arr_list[i])
    return A

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [76]:
multiple_matrix_addition([A,A,B,B,B])

array([[ 3,  8],
       [13, 18]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [78]:
A.shape[0]

2

In [79]:
def can_multiply(array_a, array_b):
    if array_a.shape[1] == array_b.shape[0]:
        print("Shape of new array will be ({},{})".format(array_a.shape[0], array_b.shape[1]))
        return True
    else:
        print("Matrices incompatible for multiplication")
        return False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [81]:
can_multiply(A, B)

Shape of new array will be (2,2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [82]:
C = np.array([[0,1],[2,3],[4,5]])
print(C)

[[0 1]
 [2 3]
 [4 5]]


**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [83]:
can_multiply(A, C)

Matrices incompatible for multiplication


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [85]:
# Result is different because multiplying matrices is not commutative.
# AC != CA

In [84]:
can_multiply(C, A)

Shape of new array will be (3,2)


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [86]:
def matrix_multiplication(array_a, array_b):
    if can_multiply(array_a, array_b):
        return array_a.dot(array_b)

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [87]:
matrix_multiplication(C, B)

Shape of new array will be (3,2)


array([[ 3,  4],
       [11, 16],
       [19, 28]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [88]:
matrix_multiplication(A, C)

Matrices incompatible for multiplication
