# Tensors

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [1]:
import torch
import numpy as np

### Tensor initialization

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [6]:
type(data), data
type(x_data), x_data

(list, [[1, 2], [3, 4]])

(torch.Tensor,
 tensor([[1, 2],
         [3, 4]]))

In [12]:
np_array = np.array(data)
np_array
x_np = torch.from_numpy(np_array)
x_np
x_np = torch.tensor(np_array)
x_np

array([[1, 2],
       [3, 4]])

tensor([[1, 2],
        [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [16]:
x_data
x_data.dtype

tensor([[1, 2],
        [3, 4]])

torch.int64

In [13]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [17]:
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.1330, 0.5152],
        [0.0188, 0.7659]])

In [20]:
shape = (2,3,)
shape

(2, 3)

In [22]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor
ones_tensor
zeros_tensor

tensor([[0.5816, 0.5332, 0.7499],
        [0.6986, 0.8341, 0.8444]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])