# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [45]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [46]:
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [47]:
arr6 = np.zeros(10, dtype="int")
arr6[4] = 1
arr6

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [48]:
# Random Values ranging from 10 to 49
arr7 = np.random.randint(10,50, size=(10))
print(arr7)

print()

# An array starting at 10 and ending at 49
arr7 = np.arange(10, 50)
print(arr7)

[44 18 28 13 25 19 20 41 34 20]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [49]:
arr8 = np.random.randint(1,11, size=10)
print(arr8)
print(arr8[::-1])

[ 6  6  2  7  9  1  9  9 10  1]
[ 1 10  9  9  1  9  7  2  6  6]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [50]:
arr9 = np.arange(9)
print(arr9)
arr9.reshape(3,3)

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [51]:
arr10 = np.array([1,2,0,0,4,0])
print(arr10)
print(arr10.nonzero())

[1 2 0 0 4 0]
(array([0, 1, 4]),)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [52]:
arr12 = np.random.random(size=(3,3))
arr12

array([[0.26634417, 0.83403839, 0.56197562],
       [0.02007229, 0.28943128, 0.71628481],
       [0.66199406, 0.21192233, 0.72306878]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [53]:
arr13 = np.random.rand(10,10)
print(arr13)
print(np.min(arr13))
print(np.max(arr13))

[[0.90483483 0.38739521 0.74886311 0.61934289 0.19800273 0.81899623
  0.64174576 0.9603255  0.65659964 0.59842301]
 [0.29725262 0.78070377 0.1011732  0.43991607 0.97821816 0.70143539
  0.99588151 0.21395528 0.60339099 0.68262308]
 [0.41541908 0.08937355 0.3316559  0.60381069 0.92349434 0.66128345
  0.40316848 0.7526383  0.83863275 0.19504529]
 [0.96412748 0.14824561 0.85469373 0.78551703 0.49025514 0.43462293
  0.82877897 0.5629039  0.46093338 0.98903479]
 [0.89964534 0.72082409 0.63468408 0.67357912 0.35878022 0.1687945
  0.45806875 0.42992649 0.53487176 0.97346313]
 [0.6902275  0.5118941  0.3785102  0.92036641 0.42336241 0.78510616
  0.52303957 0.4057205  0.5712533  0.51163979]
 [0.68830955 0.17298898 0.77539465 0.92019801 0.29502276 0.97843735
  0.00672653 0.18682487 0.67666962 0.78428029]
 [0.86232728 0.30333028 0.90532241 0.73104208 0.46592907 0.85169141
  0.66648061 0.72861266 0.78903304 0.41138502]
 [0.29420277 0.84405913 0.42721919 0.36047877 0.67002572 0.61725832
  0.23070674 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [54]:
arr14 = np.random.random(30)
print(arr14)
print(np.mean(arr14))

[0.05575546 0.64007792 0.20548547 0.84230482 0.25268979 0.69262729
 0.62074035 0.09510504 0.20535804 0.76284348 0.64765514 0.41070241
 0.56054875 0.67504788 0.76796278 0.1257941  0.12544662 0.25945499
 0.92635725 0.42688381 0.23349896 0.16846364 0.67120648 0.43639149
 0.30632646 0.82106773 0.77615515 0.66424677 0.37871781 0.1615619 ]
0.4638825929718261


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [55]:
border = np.ones((5,5), dtype="int")
inside = np.zeros((3,3), dtype="int")
arr15 = border
arr15[1:4,1:4] = inside
print(arr15)

# OR
print()

arr15 = np.ones((5,5), dtype="int")
arr15[1:-1, 1:-1] = 0
print(arr15)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [69]:
arr16 = np.random.randint(1,10, size=(3,3))
print(arr16)
np.pad(arr16, 1)

[[2 2 3]
 [6 2 1]
 [6 4 4]]


array([[0, 0, 0, 0, 0],
       [0, 2, 2, 3, 0],
       [0, 6, 2, 1, 0],
       [0, 6, 4, 4, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [58]:
arr18 = np.diag(np.arange(4) + 1, k=-1)
print(arr18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [59]:
arr20 = np.zeros(6*7*8)
arr20[99] = 1
arr20 = arr20.reshape(6,7,8)
index = np.where(arr20 == 1)
print(index)
print()

# OR
print(np.unravel_index(100, (6,7,8)))

(array([1]), array([5]), array([3]))

(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [60]:
# Generate a 5x5 normalized matrix
arr22 = np.random.normal(size=(5,5))
print(arr22)
print()

# this uses probability thoery
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[ 0.95824296  0.29050304  0.89974806  1.37573986 -1.18380162]
 [-0.90045336 -0.40942729  0.22098922 -0.85097263 -0.40019235]
 [-1.41865831 -0.65764294  0.27834527 -1.2991151  -1.61927922]
 [ 0.37866392 -0.38499539  0.13088264  1.56405143  0.2879894 ]
 [ 1.23431725  0.26267204  0.92739381 -2.37683116  0.40226367]]

[[0.39551361 0.47639295 0.75438038 0.35292627 0.86490712]
 [0.44776553 0.37370528 0.23350477 0.82818962 0.31403966]
 [0.48974683 0.9304275  0.81462627 0.511085   0.        ]
 [0.42560127 0.54683764 0.09758351 0.00956327 1.        ]
 [0.0413865  0.04897263 0.08514593 0.48368058 0.09508092]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [95]:
arr25 = np.random.randint(10, size=20)
print(arr25)
filter_array = [num <= 3 or num >= 8 for num in arr25]
print(filter_array)
arr25 = arr25[filter_array]
print(arr25)

print()

#Or maybe this is what they were asking?
arr25 = np.random.randint(10, size=20)
filter_array = [num >= 3 and num <= 8 for num in arr25]
print(arr25)
print(filter_array)
arr25 = np.negative(arr25, out=arr25, where=filter_array)
print(arr25)




[7 3 4 5 7 6 3 2 7 3 0 6 9 1 8 5 7 3 0 2]
[False, True, False, False, False, False, True, True, False, True, True, False, True, True, True, False, False, True, True, True]
[3 3 2 3 0 9 1 8 3 0 2]

[3 9 0 7 5 5 6 2 3 2 6 7 0 3 1 1 1 7 5 5]
[True, False, False, True, True, True, True, False, True, False, True, True, False, True, False, False, False, True, True, True]
[-3  9  0 -7 -5 -5 -6  2 -3  2 -6 -7  0 -3  1  1  1 -7 -5 -5]


#### 29. How to round away from zero a float array ? (★☆☆)

In [62]:
# IDK what this means

#### 30. How to find common values between two arrays? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [63]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-63-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [8]:
arr40 = np.random.random(10)
arr40.sort()
arr40

array([0.03221995, 0.08028975, 0.15428631, 0.4208199 , 0.48575524,
       0.65093271, 0.83546403, 0.83711007, 0.85334719, 0.89354512])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

[6 2 4 1 4 1 0 0 6 4]


6

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 83. How to find the most frequent value in an array?

#### 89. How to get the n largest values of an array (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)