In [1]:
import numpy as np

In [35]:
a = np.array([1, 2, 3, 4, 5], dtype="int16")
print(a)

[1 2 3 4 5]


In [8]:
b = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print(b)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [11]:
c = np.array([[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]])
print(c)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [12]:
# Get number of dimensions
print(a.ndim, b.ndim, c.ndim)

1 2 3


In [13]:
# Get size of dimensions
print(a.shape, b.shape, c.shape)

# a is 5x1
# b is 2x5
# c is 1x3x5

(5,) (2, 5) (1, 3, 5)


In [67]:
c.reshape(3,5)
print(c)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [38]:
#Get datatype
print(a.dtype)

# Get memory size of each item in the array (in bytes)
print(a.itemsize)

# Get number of elements in the array
print(a.size)

# Get total memory size of the array
print(a.nbytes)
# or
print(a.size * a.itemsize)

int16
2
5
10
10


In the above example, the data type is "int16" which reserves 16 bits for each number.

The item size is 2 bytes, because 16 bits is 2 bytes

There are 5 elements in the array

Therefore the total size of the array in bytes is 10 bytes (5 elements * 2 bytes per element)

### Accessing elements in an array

In [45]:
multiplication_table = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                                 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                 [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24],
                                 [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36],
                                 [0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48],
                                 [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
                                 [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72],
                                 [0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84],
                                 [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96],
                                 [0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108],
                                 [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120],
                                 [0, 11, 22, 33, 44, 55, 66, 77, 88, 99, 110, 121, 132],
                                 [0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144]])

In [46]:
print(multiplication_table)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   2   3   4   5   6   7   8   9  10  11  12]
 [  0   2   4   6   8  10  12  14  16  18  20  22  24]
 [  0   3   6   9  12  15  18  21  24  27  30  33  36]
 [  0   4   8  12  16  20  24  28  32  36  40  44  48]
 [  0   5  10  15  20  25  30  35  40  45  50  55  60]
 [  0   6  12  18  24  30  36  42  48  54  60  66  72]
 [  0   7  14  21  28  35  42  49  56  63  70  77  84]
 [  0   8  16  24  32  40  48  56  64  72  80  88  96]
 [  0   9  18  27  36  45  54  63  72  81  90  99 108]
 [  0  10  20  30  40  50  60  70  80  90 100 110 120]
 [  0  11  22  33  44  55  66  77  88  99 110 121 132]
 [  0  12  24  36  48  60  72  84  96 108 120 132 144]]


In [47]:
#array[row, column]
multiplication_table[3, 5]

15

use standard slicing syntax to access entire rows and columns

In [48]:
multiplication_table[12,:]

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144])

## Initializing arrays

In [63]:
arr0 = np.ones((5,5))
arr0[1:4, 1:4] = 0
arr0[2,2] = 9
print(arr0)

# Also you can substitute smaller arrays into larger arrays.
# i.e. you can choose a slice of a larger array that is the same size as a smaller array and
# replace that slice with the smaller array

arr1 = np.ones((5,5))
arr2 = np.zeros((3,3))
arr3 = np.full((1,1), 9)
arr2[1,1] = arr3
arr1[1:4, 1:4] = arr2
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Use the `copy()` method to make a copy of an array

### Math