# Variable Selection

In [1]:
import pandas as pd
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
df_numeric = pd.read_csv("df_numeric.csv")
df_numeric.head()

MSSubClass  LotFrontage  LotArea  Street  LotShape  Utilities  LandSlope  \
0          60         65.0     8450       2         4          4          3   
1          20         80.0     9600       2         4          4          3   
2          60         68.0    11250       2         3          4          3   
3          70         60.0     9550       2         3          4          3   
4          60         84.0    14260       2         3          4          3   

   OverallQual  OverallCond  YearBuilt  ...  MoSold  YrSold  SalePrice  \
0            7            5       2003  ...       2    2008     208500   
1            6            8       1976  ...       5    2007     181500   
2            7            5       2001  ...       9    2008     223500   
3            7            5       1915  ...       2    2006     140000   
4            8            5       2000  ...      12    2008     250000   

   GarageYrBlt_missing_ind  LotFrontage_missing_ind  MasVnrArea_missing_ind  \
0                        0                        0                       0   
1                        0                        0                       0   
2                        0                        0                       0   
3                        0                        0                       0   
4                        0                        0                       0   

   1stFlrSF_log  1stFlr_2ndFlr_SF  OverallGrade  SimplGarageQual  
0      6.752270              1710            35                1  
1      7.140453              1262            48                1  
2      6.824374              1786            35                1  
3      6.867974              1717            35                1  
4      7.043160              2198            40                1  

[5 rows x 60 columns]

### drop the target variable from the dataframe before doing feature selection so we don't change it accidentally

In [4]:
target = df_numeric["SalePrice"]
df_numeric.drop("SalePrice", axis=1, inplace=True)

### Removing features with small variance

small variance = small predicting power

In [5]:
from sklearn.feature_selection import VarianceThreshold

In [6]:
vt = VarianceThreshold(0.1)
df_transformed = vt.fit_transform(df_numeric)

In [7]:
df_numeric.shape
df_transformed.shape

# 9 features were removed

(1458, 59)

(1458, 50)

In [8]:
df_numeric.head(2)
df_transformed

MSSubClass  LotFrontage  LotArea  Street  LotShape  Utilities  LandSlope  \
0          60         65.0     8450       2         4          4          3   
1          20         80.0     9600       2         4          4          3   

   OverallQual  OverallCond  YearBuilt  ...  MiscVal  MoSold  YrSold  \
0            7            5       2003  ...        0       2    2008   
1            6            8       1976  ...        0       5    2007   

   GarageYrBlt_missing_ind  LotFrontage_missing_ind  MasVnrArea_missing_ind  \
0                        0                        0                       0   
1                        0                        0                       0   

   1stFlrSF_log  1stFlr_2ndFlr_SF  OverallGrade  SimplGarageQual  
0      6.752270              1710            35                1  
1      7.140453              1262            48                1  

[2 rows x 59 columns]

array([[   60.,    65.,  8450., ...,     0.,  1710.,    35.],
       [   20.,    80.,  9600., ...,     0.,  1262.,    48.],
       [   60.,    68., 11250., ...,     0.,  1786.,    35.],
       ...,
       [   70.,    66.,  9042., ...,     0.,  2340.,    63.],
       [   20.,    68.,  9717., ...,     0.,  1078.,    30.],
       [   20.,    75.,  9937., ...,     0.,  1256.,    30.]])

**Turning df_transformed back into a dataframe**

In [9]:
vt.get_support()

df_numeric.columns

df_numeric.columns[vt.get_support()]

array([ True,  True,  True, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False])

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'Street', 'LotShape',
       'Utilities', 'LandSlope', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'MasVnrArea', 'ExterQual', 'ExterCond', 'BsmtQual',
       'BsmtCond', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', 'HeatingQC', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageYrBlt', 'GarageCars',
       'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'GarageYrBlt_missing_ind',
       'LotFrontage_missing_ind', 'MasVnrArea_missing_ind', '1stFlrSF_log',
       '1stFlr_2ndFlr_SF', 'OverallGrade', 'SimplGarageQual'],
      dtype='object')

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'LotShape', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'BsmtQual', 'BsmtCond', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'HeatingQC',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea',
       'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'LotFrontage_missing_ind', '1stFlr_2ndFlr_SF',
       'OverallGrade'],
      dtype='object')

In [10]:
df_transformed = pd.DataFrame(df_transformed, columns=df_numeric.columns[vt.get_support()])
df_transformed.head()

MSSubClass  LotFrontage  LotArea  LotShape  OverallQual  OverallCond  \
0        60.0         65.0   8450.0       4.0          7.0          5.0   
1        20.0         80.0   9600.0       4.0          6.0          8.0   
2        60.0         68.0  11250.0       3.0          7.0          5.0   
3        70.0         60.0   9550.0       3.0          7.0          5.0   
4        60.0         84.0  14260.0       3.0          8.0          5.0   

   YearBuilt  YearRemodAdd  MasVnrArea  ExterQual  ...  EnclosedPorch  \
0     2003.0        2003.0       196.0        4.0  ...            0.0   
1     1976.0        1976.0         0.0        3.0  ...            0.0   
2     2001.0        2002.0       162.0        4.0  ...            0.0   
3     1915.0        1970.0         0.0        3.0  ...          272.0   
4     2000.0        2000.0       350.0        4.0  ...            0.0   

   3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  \
0        0.0          0.0       0.0      0.0     2.0  2008.0   
1        0.0          0.0       0.0      0.0     5.0  2007.0   
2        0.0          0.0       0.0      0.0     9.0  2008.0   
3        0.0          0.0       0.0      0.0     2.0  2006.0   
4        0.0          0.0       0.0      0.0    12.0  2008.0   

   LotFrontage_missing_ind  1stFlr_2ndFlr_SF  OverallGrade  
0                      0.0            1710.0          35.0  
1                      0.0            1262.0          48.0  
2                      0.0            1786.0          35.0  
3                      0.0            1717.0          35.0  
4                      0.0            2198.0          40.0  

[5 rows x 50 columns]

### Removing Correlated (Redundant) Features

In [11]:
df_corr = df_transformed.corr().abs()
df_corr.head()

MSSubClass  LotFrontage   LotArea  LotShape  OverallQual  \
MSSubClass     1.000000     0.374663  0.142033  0.116473     0.032522   
LotFrontage    0.374663     1.000000  0.276157  0.168947     0.218782   
LotArea        0.142033     0.276157  1.000000  0.303146     0.091392   
LotShape       0.116473     0.168947  0.303146  1.000000     0.190817   
OverallQual    0.032522     0.218782  0.091392  0.190817     1.000000   

             OverallCond  YearBuilt  YearRemodAdd  MasVnrArea  ExterQual  ...  \
MSSubClass      0.059275   0.027757      0.040503    0.023423   0.015982  ...   
LotFrontage     0.050342   0.111102      0.075812    0.151042   0.146183  ...   
LotArea         0.002723   0.007462      0.007500    0.083715   0.040373  ...   
LotShape        0.032042   0.226674      0.172670    0.076833   0.180443  ...   
OverallQual     0.090442   0.571368      0.549827    0.398785   0.723286  ...   

             EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea   MiscVal  \
MSSubClass        0.012002   0.043813     0.026004  0.008090  0.007675   
LotFrontage       0.013934   0.066350     0.042141  0.100395  0.001732   
LotArea           0.016505   0.021362     0.045288  0.036491  0.039072   
LotShape          0.094430   0.034485     0.066678  0.011531  0.029176   
OverallQual       0.113176   0.030991     0.066298  0.044758  0.031238   

               MoSold    YrSold  LotFrontage_missing_ind  1stFlr_2ndFlr_SF  \
MSSubClass   0.013581  0.021386             1.527907e-02          0.072976   
LotFrontage  0.023697  0.007099             3.812539e-17          0.321809   
LotArea      0.005744  0.013699             1.262602e-01          0.234489   
LotShape     0.031968  0.037661             3.128919e-01          0.194933   
OverallQual  0.072531  0.026575             3.434924e-02          0.597633   

             OverallGrade  
MSSubClass       0.011288  
LotFrontage      0.141997  
LotArea          0.076785  
LotShape         0.133939  
OverallQual      0.715808  

[5 rows x 50 columns]

In [12]:
indices = np.where(df_corr > 0.8)
indices

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 18, 19, 20, 20, 21, 22, 23, 23, 23, 24, 25, 26, 27, 28, 29,
        29, 29, 30, 31, 32, 33, 33, 34, 34, 35, 35, 36, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 48, 48, 49]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 20, 19, 18, 20, 21, 22, 23, 29, 48, 24, 25, 26, 27, 28, 23,
        29, 48, 30, 31, 32, 33, 34, 33, 34, 35, 36, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 23, 29, 48, 49]))

In [13]:
type(indices)

tuple

In [14]:
# These for loops produce the same result

for x, y in zip(indices[0], indices[1]):
    print(x, y)
    
for x, y in zip(*indices):
    print(x, y)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17
18 18
18 20
19 19
20 18
20 20
21 21
22 22
23 23
23 29
23 48
24 24
25 25
26 26
27 27
28 28
29 23
29 29
29 48
30 30
31 31
32 32
33 33
33 34
34 33
34 34
35 35
35 36
36 35
36 36
37 37
38 38
39 39
40 40
41 41
42 42
43 43
44 44
45 45
46 46
47 47
48 23
48 29
48 48
49 49
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17
18 18
18 20
19 19
20 18
20 20
21 21
22 22
23 23
23 29
23 48
24 24
25 25
26 26
27 27
28 28
29 23
29 29
29 48
30 30
31 31
32 32
33 33
33 34
34 33
34 34
35 35
35 36
36 35
36 36
37 37
38 38
39 39
40 40
41 41
42 42
43 43
44 44
45 45
46 46
47 47
48 23
48 29
48 48
49 49


In [15]:
index_pairs = []

for x, y in zip(*indices):
    if (x != y) and (x < y):
        index_pairs.append((df_corr.index[x], df_corr.columns[y]))
        
index_pairs

[('TotalBsmtSF', '1stFlrSF'),
 ('GrLivArea', 'TotRmsAbvGrd'),
 ('GrLivArea', '1stFlr_2ndFlr_SF'),
 ('TotRmsAbvGrd', '1stFlr_2ndFlr_SF'),
 ('GarageCars', 'GarageArea'),
 ('GarageQual', 'GarageCond')]

In [16]:
for idx in index_pairs:
    try:
        df_transformed.drop(idx[1], axis=1, inplace=True)
    except KeyError:
        pass

In [17]:
df_transformed.shape

# 5 more features dropped

(1458, 45)

### Forward Regression. Selecting the K best features (K features most correlated with the target variable)

In [18]:
from sklearn.feature_selection import f_regression, SelectKBest

In [19]:
skb = SelectKBest(f_regression, k=10)
X = skb.fit_transform(df_transformed, target)
X

array([[7.000e+00, 2.003e+03, 4.000e+00, ..., 4.000e+00, 2.000e+00,
        3.500e+01],
       [6.000e+00, 1.976e+03, 3.000e+00, ..., 3.000e+00, 2.000e+00,
        4.800e+01],
       [7.000e+00, 2.001e+03, 4.000e+00, ..., 4.000e+00, 2.000e+00,
        3.500e+01],
       ...,
       [7.000e+00, 1.941e+03, 5.000e+00, ..., 4.000e+00, 1.000e+00,
        6.300e+01],
       [5.000e+00, 1.950e+03, 3.000e+00, ..., 4.000e+00, 1.000e+00,
        3.000e+01],
       [5.000e+00, 1.965e+03, 4.000e+00, ..., 3.000e+00, 1.000e+00,
        3.000e+01]])

In [20]:
skb.get_support().shape

df_transformed.shape

(45,)

(1458, 45)

In [21]:
X = pd.DataFrame(X, columns=df_transformed.columns[skb.get_support()])
X

OverallQual  YearBuilt  ExterQual  BsmtQual  TotalBsmtSF  GrLivArea  \
0             7.0     2003.0        4.0       4.0        856.0     1710.0   
1             6.0     1976.0        3.0       4.0       1262.0     1262.0   
2             7.0     2001.0        4.0       4.0        920.0     1786.0   
3             7.0     1915.0        3.0       3.0        756.0     1717.0   
4             8.0     2000.0        4.0       4.0       1145.0     2198.0   
...           ...        ...        ...       ...          ...        ...   
1453          6.0     1999.0        3.0       4.0        953.0     1647.0   
1454          6.0     1978.0        3.0       4.0       1542.0     2073.0   
1455          7.0     1941.0        5.0       3.0       1152.0     2340.0   
1456          5.0     1950.0        3.0       3.0       1078.0     1078.0   
1457          5.0     1965.0        4.0       3.0       1256.0     1256.0   

      FullBath  KitchenQual  GarageCars  OverallGrade  
0          2.0          4.0         2.0          35.0  
1          2.0          3.0         2.0          48.0  
2          2.0          4.0         2.0          35.0  
3          1.0          4.0         3.0          35.0  
4          2.0          4.0         3.0          40.0  
...        ...          ...         ...           ...  
1453       2.0          3.0         2.0          30.0  
1454       2.0          3.0         2.0          36.0  
1455       2.0          4.0         1.0          63.0  
1456       1.0          4.0         1.0          30.0  
1457       1.0          3.0         1.0          30.0  

[1458 rows x 10 columns]

# Linear Regression with statsmodels

In [22]:
import statsmodels.api as sm

In [23]:
X = sm.add_constant(X)

/Users/zacharyargentin/opt/anaconda3/envs/bootcamp/lib/python3.8/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [24]:
X

const  OverallQual  YearBuilt  ExterQual  BsmtQual  TotalBsmtSF  \
0       1.0          7.0     2003.0        4.0       4.0        856.0   
1       1.0          6.0     1976.0        3.0       4.0       1262.0   
2       1.0          7.0     2001.0        4.0       4.0        920.0   
3       1.0          7.0     1915.0        3.0       3.0        756.0   
4       1.0          8.0     2000.0        4.0       4.0       1145.0   
...     ...          ...        ...        ...       ...          ...   
1453    1.0          6.0     1999.0        3.0       4.0        953.0   
1454    1.0          6.0     1978.0        3.0       4.0       1542.0   
1455    1.0          7.0     1941.0        5.0       3.0       1152.0   
1456    1.0          5.0     1950.0        3.0       3.0       1078.0   
1457    1.0          5.0     1965.0        4.0       3.0       1256.0   

      GrLivArea  FullBath  KitchenQual  GarageCars  OverallGrade  
0        1710.0       2.0          4.0         2.0          35.0  
1        1262.0       2.0          3.0         2.0          48.0  
2        1786.0       2.0          4.0         2.0          35.0  
3        1717.0       1.0          4.0         3.0          35.0  
4        2198.0       2.0          4.0         3.0          40.0  
...         ...       ...          ...         ...           ...  
1453     1647.0       2.0          3.0         2.0          30.0  
1454     2073.0       2.0          3.0         2.0          36.0  
1455     2340.0       2.0          4.0         1.0          63.0  
1456     1078.0       1.0          4.0         1.0          30.0  
1457     1256.0       1.0          3.0         1.0          30.0  

[1458 rows x 11 columns]

In [27]:
y = target

In [28]:
lin_reg = sm.OLS(y, X)

In [29]:
type(lin_reg)

statsmodels.regression.linear_model.OLS

In [30]:
model = lin_reg.fit()

In [31]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.835
Model:                            OLS   Adj. R-squared:                  0.834
Method:                 Least Squares   F-statistic:                     732.0
Date:                Thu, 12 Aug 2021   Prob (F-statistic):               0.00
Time:                        12:58:17   Log-Likelihood:                -17206.
No. Observations:                1458   AIC:                         3.443e+04
Df Residuals:                    1447   BIC:                         3.449e+04
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -8.992e+05   8.93e+04    -10.069      0.000   -1.07e+06   -7.24e+05
OverallQual   5507.5419   1492.215      3.691      0.000    2580.406    8434.678
YearBuilt      392.2864     47.578      8.245      0.000     298.958     485.615
ExterQual     1.447e+04   2498.908      5.789      0.000    9564.917    1.94e+04
BsmtQual       920.7862   1443.233      0.638      0.524   -1910.266    3751.839
TotalBsmtSF     42.1385      2.705     15.581      0.000      36.833      47.444
GrLivArea       66.8550      2.624     25.476      0.000      61.707      72.003
FullBath     -1.122e+04   2268.762     -4.945      0.000   -1.57e+04   -6768.180
KitchenQual   1.147e+04   1981.665      5.788      0.000    7582.652    1.54e+04
GarageCars    9314.4359   1565.232      5.951      0.000    6244.069    1.24e+04
OverallGrade  1078.1960    150.946      7.143      0.000     782.100    1374.292
==============================================================================
Omnibus:                      574.228   Durbin-Watson:                   1.967
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5878.203
Skew:                           1.540   Prob(JB):                         0.00
Kurtosis:                      12.342   Cond. No.                     2.87e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.87e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Linear Regression with Sklearn

In [32]:
from sklearn.linear_model import LinearRegression

In [35]:
regressor = LinearRegression()

In [36]:
regressor.fit(X, y)

LinearRegression()

In [38]:
# Get beta coefficients
regressor.coef_

array([     0.        ,   5507.54189138,    392.2863556 ,  14466.78601472,
          920.78618122,     42.13854481,     66.85496149, -11218.59562134,
        11469.89475761,   9314.43585305,   1078.19597724])

In [39]:
# Get R squared value
regressor.score(X, y)

0.83494920713919