# Train test split walkthrough

In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### generate data

In [1]:
X = list(range(10))
X

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
y = [x*x for x in X]
y

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### split and shuffle data

In [3]:
import sklearn.model_selection as model_selection

In [9]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size=0.75, random_state=101)

In [10]:
X_train
X_test
y_train
y_test

[4, 9, 3, 5, 7, 6, 1]

[8, 2, 0]

[16, 81, 9, 25, 49, 36, 1]

[64, 4, 0]

In [34]:
from sklearn.model_selection import KFold
import numpy as np

In [97]:
kf = KFold(n_splits=5, shuffle=True)
X = np.array(X)
y = np.array(y)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train, X_test)
    print(y_train, y_test)

[0 1 3 4 6 7 8 9] [2 5]
[ 0  1  9 16 36 49 64 81] [ 4 25]
[0 1 2 3 4 5 6 7] [8 9]
[ 0  1  4  9 16 25 36 49] [64 81]
[0 2 4 5 6 7 8 9] [1 3]
[ 0  4 16 25 36 49 64 81] [1 9]
[1 2 3 4 5 7 8 9] [0 6]
[ 1  4  9 16 25 49 64 81] [ 0 36]
[0 1 2 3 5 6 8 9] [4 7]
[ 0  1  4  9 25 36 64 81] [16 49]
